// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0d6LeHD5n7nI3LqyVAHgChNs-QhW98A',
    appId: '1:291637501723:web:35da090f74f0e9b4c63dbe',
    messagingSenderId: '291637501723',
    projectId: 'guardshifts-52452',
    authDomain: 'guardshifts-52452.firebaseapp.com',
    storageBucket: 'guardshifts-52452.appspot.com',
    measurementId: 'G-HJTW8CRHG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kGZDwyyrQ2zdDBHFK3_OaihdiAvTRWA',
    appId: '1:291637501723:android:11538f52fab011dec63dbe',
    messagingSenderId: '291637501723',
    projectId: 'guardshifts-52452',
    storageBucket: 'guardshifts-52452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfVqhDgb3TKwowAFNg7-7kWhagBF35kg',
    appId: '1:291637501723:ios:5f90664e78197217c63dbe',
    messagingSenderId: '291637501723',
    projectId: 'guardshifts-52452',
    storageBucket: 'guardshifts-52452.appspot.com',
    iosClientId: '291637501723-o4ir5jc0ldml10aq5kjfda0si4qv40t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shidts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfVqhDgb3TKwowAFNg7-7kWhagBF35kg',
    appId: '1:291637501723:ios:fc8cbb7e369fb224c63dbe',
    messagingSenderId: '291637501723',
    projectId: 'guardshifts-52452',
    storageBucket: 'guardshifts-52452.appspot.com',
    iosClientId: '291637501723-d4v9i53abvd2ve495mvf8osl10fv106n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shidts.RunnerTests',
  );
}
